desc "Upload to DeployGate"
lane :DEV do
  gym
  deploygate(
    api_token: 'eca9d549fd7fc103c012494c33aa06f52c4920db',
    user: 'yaizawa',
    message: "Fastlane build new-function#{lane_context[SharedValues::BUILD_NUMBER]}",
  )
end